### ISSUE TITLE
jwks-RSA Support

### ISSUE THREAD

**Issue by dobby5** [Thream/socketio-jwt#1]
### Description

The addition of the support of jwks-RSA (https://www.npmjs.com/package/jwks-rsa)

### Describe the solution you'd like

Support for this feature can be seen in the fork of ssnxd (https://www.npmjs.com/package/@ssnxd/socketio-jwt/v/4.5.3). 
The original repo does not support this feature as far as I know.

Example of the implementation currently in use:

    io.sockets
        .use(
            authorize({
                algorithms: ['RS256'],
                secret: jwksRsa.expressJwtSecret({
                    cache: true,
                    rateLimit: true,
                    jwksRequestsPerMinute: 5,
                    jwksUri: `https://${process.env.DOMAIN}/oauth2/jwks`
                }),
                timeout: 15000
            })
        )

**Comment by Divlo** [comment]
Sure! @dobby5 
I just added the option `algorithms` to `authorize` options so you can change the algorithms used (on develop branch, not released yet to npm).

The `timeout` option will not be implemented since we are using the "One roundtrip" way with the `handshake: true` option described in the old package. (explained why there: https://github.com/auth0-community/auth0-socketio-jwt/issues/178#issuecomment-751945050).

Concerning, implementing support for `jwks-rsa` : 
Currently, you can only pass a string to the `secret` option maybe we could also provide the way to pass a callback and that callback should return the secret to use to verify if the jwt is valid or not.
I've never used this library, so could you tell me what return this method and what it does :
```js
jwksRsa.expressJwtSecret({
  cache: true,
  rateLimit: true,
  jwksRequestsPerMinute: 5,
  jwksUri: `https://${process.env.DOMAIN}/oauth2/jwks`
})
```
Thanks for your feedback and your help! :+1:

**Comment by dobby5** [comment]
Since it is always difficult to write something that you don't use yourself or can't test, I wrote the function for the jwks-RSA implementation.

I have created a fork for it.
I am not familiar with typescript. I usually write pure javascript code.

Therefore, I would like to ask you to edit my comments. After that I will make the last changes.
I wrote the code so that we don't have to add a new dependency that would pollute your rewrite.

**Comment by Divlo** [comment]
You could open a PR, so I would be able to review your code better.
I already read your code changes introduced in https://github.com/dobby5/socketio-jwt/commit/bf6a6542597378d924ce7c329fb7f498a1bef836.

As I said, we should not support a specific library but instead maybe add a way to support library like `jwks-rsa` without calling methods of this library.

Instead of doing something like this (also as side note you should follow `ts-standard` linting rules) :
```ts
secret.getSigningKey(decodedToken.header.kid, function (err: any, key: { publicKey: any; rsaPublicKey: any }) {
  var signingKey = key.publicKey || key.rsaPublicKey;
});
```
We could pass a callback to the `secret` option and do your extra logic with that method call etc.
Also, you're creating a new variable `signingKey` but you're not using it anywhere.
From what I understood, what does really matter is that `jwks-rsa` allows you to have a specific logic to get your secret but at the end, we still have a secret to verify that the jwt is valid or not so we could have a callback function to get this secret.
Hopefully, I'm clear now.

**Comment by dobby5** [comment]
Hey Divlo,

sorry I have little time today, so today a little shorter the answer.

Nevertheless, I would like to praise the cooperation with you once. I find it very pleasant to work with you on the functions.

I have made a pull request and send you the javascript code of my version. Maybe you can find a better port for it. My solution also works with callbacks.

I thank you and if you also celebrate today new year.
Then I wish you a happy new year.

**Comment by Divlo** [comment]
Happy new year! :tada: 

Excuse me if I bother you and if it takes time but your code is not ready at all ready to be merged.
Your code don't follow the `ts-standard` linting rules.
There a several bad things in your implementation, I'm always looking for contributors and collaborators but I'd rather to be honest, hopefully we can find a solution to implement your needs.
What does the code above represent ? The code of the library ?
Why are you not editing your PR code directly instead of sending me the code in issue comments ?

You never told me what does this method returns :
```ts
jwksRsa.expressJwtSecret({
  cache: true,
  rateLimit: true,
  jwksRequestsPerMinute: 5,
  jwksUri: `https://${process.env.DOMAIN}/oauth2/jwks`
})
```

So could you tell me how do you verify a jwt token with `jwks-rsa` ? Can I do something like that to verify a JWT token (pseudo not all variables are defined) : 
```ts
const jwt = require('jsonwebtoken')

onst client = await jwksRsa({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: `https://${process.env.DOMAIN}:${process.env.PORT}/oauth2/jwks`
})

client.getSigningKey(kid, (err, key) => {
  const signingKey = key.getPublicKey()
    jwt.verify(token, signingKey, function (err, payload) {
        if (err != null) {
          console.log('jwt is invalid')
          return
        }
        console.log('jwt is valid')
    })
})
```
To verify your token, you need to first decode it before verify if it is valid or not ?

If you tell me how to verify that a jwt token is valid or not, then I would be most likely be able to implement compatibility for `jwks-rsa`.

**Comment by dobby5** [comment]
All good things cost time and should also cost time.
Otherwise it will not be a good code.

I have a little more time today.

As I said, I am not familiar with TS. I prefer to write a pure javascript code, because it brings more performance for me.
But the advantages TS brings are not to be disguised and has its raison d'être.

The code written above contains the function to process the jwks-rsa (JwksClient) function. The output of jwksRsa.expressJwtSecret (now jwksRsa) is a "JwksClient" function.
I changed jwksRsa.expressJwtSecret to jwksRsa so that the implementation is not just tailored to express.

I'll send you the code so you can rewrite it in TS if you're so kind. My time resources don't allow me to get familiar with TS right now. Nevertheless I would like to contribute my part to the project.

I will close my PR. I don't think it makes sense to keep it open, because the code is very unattractive.

I need the decode to read out the kidId. After that the code is verified via "verify".
