### ISSUE TITLE
No timeout option?

### ISSUE THREAD

**Issue by skipper09** [Thream/socketio-jwt#34]
I am switching from socketio-jwt to @thream/socketio-jwt.
My original authorization options object include a timeout. I don't see anything about timeouts not being supported in the documentation despite this item being forked from socketio-jwt.

TS error: 

``Argument of type '{ secret: string; timeout: number; algorithms: "HS256"[]; }' is not assignable to parameter of type 'AuthorizeOptions'.
  Object literal may only specify known properties, and 'timeout' does not exist in type 'AuthorizeOptions'.ts(2345) ``

## The current behavior
I cannot add a timeout option in the AuthorizeOptions

## The expected behavior
I can include a timeout option in the AuthorizeOptions

I feel like this is a bug but if this should be feature request instead, feel free to change th label. Thanks!

**Comment by Divlo** [comment]
As I said in this comment : https://github.com/auth0-community/auth0-socketio-jwt/issues/178#issuecomment-751945050

The idea of this package is not to support all the features from the original one, since the original one had several ways to use the package, instead what we want is to have only single way to use it, but it is always working, so it's much easier to use it and everyone use it same way.

Example : 

- In the old package you could connect like that
```js
io.sockets
.on('connection', socketioJwt.authorize({
  secret: 'your secret or public key',
  timeout: 15000 // 15 seconds to send the authentication message
}))
.on('authenticated', (socket) => {
  //this socket is authenticated, we are good to handle more events from it.
  console.log(`hello! ${socket.decoded_token.name}`);
});
```
- Or like that  (One roundtrip) :
```js
io.use(socketioJwt.authorize({
  secret: 'your secret or public key',
  handshake: true
}));

io.on('connection', (socket) => {
  console.log('hello!', socket.decoded_token.name);
});
```

We dedcided to take the "One roundtrip" way for this package, so you don't need specifcy `handshake: true` in the options since it's by default and the only way to use it.

With this option, it seems like there is no `timeout` option.

Could you tell us, what are you use cases ? Thanks for creating this issue. @skipper09 
Maybe you don't need to have the timeout option, and you could use the one roundtrip way.

**Comment by skipper09** [comment]
Hi @Divlo, thanks for quick reply! I've realized that our codebase does not need the timeout option and the new option will work for us. _However_, I am in a situation where I need to send the token in via the query field in the client connect options, but it looks like the socketio-jwt does not recognize that as a source for the token. 

Current behavior:
Tokens can only be sent in via the extraHeaders option. Tokens sent via the query field are not accepted.
However, socket.io-client does not utilize the extra headers option if transports is set to websockets only, which is the case for my app.

Expected behavior:
Tokens sent in via the query field are also accepted.

https://socket.io/docs/v3/client-initialization/ -> see the extraHeaders option a little more than halfway down the page

**Comment by Divlo** [comment]
This is relative to this comment : https://github.com/auth0-community/auth0-socketio-jwt/issues/178#issuecomment-772670402

If we decide to send the Token via query instead of the Authorization in Header, we should remove the Authorization way, the goal here is to simplify the usage of this package, so we'll only allow one way to use it, with some options but as little as possible, the thing is that it should work out of the box without configuration. Of course the goal is to satisfy the maximum of use cases while being simple to use

Do you think, we should allow to pass the token via query and remove the way to use it with the extraHeaders ?
**Note:** It is a BREAKING CHANGE**.

You're right, we should improve the `README` documentation to list all the options available, maybe it's be better to list the available options instead of the options removed from the original package. What do you think ? :smile:


@skipper09

**Comment by skipper09** [comment]
It might work by accepting only the query item instead of the authorization header, but I'm no expert. All I know is for my app, I need the query option. Maybe a poll of other users may be helpful. However if there are some cases where a user needs an authorization header then I think both should be available. 

Yes, I think listing the options is a good idea along with some statement saying the functionality is limited for simplicity compared to the original package it is forked from.

I'm going to close this bug since the original item is no longer a bug. Thanks, Divlo.

**Comment by Divlo** [comment]
I opened a new issue to track the support for `websocket`.
See: #37 

I also added in the `README`, the options for the `authorize` function! @skipper09
